name: Build and Test

on:
  push:
    branches: [ master, py3.11, github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  unix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        py: [ "2.7", "3.7", "3.8", "3.9", "3.10", "3.11.0-rc.2" ]
        rust: [ "1.41.1", "stable", "nightly" ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.py }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}
    - name: Setup Rust ${{ matrix.rust }}
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: ${{ matrix.rust }}
      continue-on-error: true
    - name: Delete rustup cache
      run: rm -rf ~/.rustup
      if: ${{ steps.rustup.outcome }} != "success"
    - name: Setup Rust (again)
      if: ${{ steps.rustup.outcome }} != "success"
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Check versions and paths
      run: |
        python -V ; rustc -V
        echo "PATH=$PATH"
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
        echo "LIBRARY_PATH=$LIBRARY_PATH"
        PYTHON_LIB=$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
        echo "PYTHON_LIB=$PYTHON_LIB"
        echo "LIBRARY_PATH=$LIBRARY_PATH:$PYTHON_LIB" >> "$GITHUB_ENV"
    - name: Remove Cargo.lock
      if: ${{ matrix.rust == 'stable' || matrix.rust == 'nightly' }}
      run: |
        rm Cargo.lock
    - name: Build and test
      run: |
        make test extensions

  windows:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        py: [ "2.7", "3.7", "3.8", "3.9", "3.10", "3.11.0-rc.2"]
        rust: [ "1.41.1", "stable" ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.py }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}
    - name: Setup Rust ${{ matrix.rust }}
      id: rustup
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Check versions and paths
      run: |
        python -V
        rustc -V
        echo PATH=$env:path
    - name: Remove Cargo.lock
      if: ${{ matrix.rust == 'stable' || matrix.rust == 'nightly' }}
      run: |
        del Cargo.lock
    - name: Build and test
      run: |
        make test
